######################################################################
# Automatically generated by qmake (3.1) Mon Apr 5 21:01:42 2021
######################################################################

QT -= gui core

TEMPLATE = subdirs
SUBDIRS = \
    seq

seq.file = seq/needleman-wunsch-seq.pro

DESTDIR = build
OBJECTS_DIR = build
MOC_DIR = build